---
title: "International Tax Poverty States"
author: "Marcus"
date: "2024-06-10"
output: html_document
---

```{r message=FALSE}
library(convergEU)
library(knitr)
library(tibble)
library(tidyverse)
library(eurostat)
library(purrr)
library(tidyr)
library(ggplot2)
library(kableExtra)
options(kableExtra.auto_format = FALSE)
library(caTools)
library(broom)
library(gridExtra)
library(flextable)
library(flexmix)
library(formattable) 
library(officer)
library(leaflet)
library(magrittr)
library(leaflet.extras)
library(png)
library(purrr)
library(htmltools)
library(htmlwidgets)
library(rmarkdown)
library(webshot)
library(webshot2)
```

```{r}
international_poverty_states_br = read.csv("international_poverty_states_br.csv")
head(international_poverty_states_br)
```


### Beta_convergence

```{r}
c(min(international_poverty_states_br$time), max(international_poverty_states_br$time))
```

```{r}
empBC = beta_conv(international_poverty_states_br,
                  time_0 = 2012,
                  time_t = 2021,
                  all_within = FALSE,
                  timeName = 'time')
empBC
```


```{r message = FALSE}
qplot(empBC$res$workTB$indic,
empBC$res$workTB$deltaIndic,
xlab="log-Indicator",
ylab="Delta-log-indicator") +
geom_abline(intercept = as.numeric(empBC$res$summary[1,2]),
slope = as.numeric(empBC$res$summary[2,2]),
colour = "red") +
geom_text(aes(label=empBC$res$workTB$countries),
hjust=0, vjust=0,colour="blue")
```

### Sigma_convergence

```{r}
mySTB <- sigma_conv(international_poverty_states_br, timeName="time")
mySTB

```

### Departure Mean

```{r}
res <- departure_mean(oriTB = international_poverty_states_br, sigmaTB = mySTB$res)
names(res$res)

```

```{r}
res$res$departures
```


```{r}
res$res$squaredContrib
```

```{r}
res$res$devianceContrib
```

```{r}
myGG <- graph_departure(res$res$departures,
timeName = "time",
displace = 0.25,
displaceh = 0.45,
dimeFontNum = 4,
myfont_scale = 1.35,
x_angle = 45,
color_rect = c("-1"='red1', "0"='gray80',"1"='lightskyblue1'),
axis_name_y = "Countries",
axis_name_x = "Time",
alpha_color = 0.9
)

myGG
```

```{r}
myGG <- graph_departure(res$res$departures[,1:10],
timeName = "time",
displace = 0.25,
displaceh = 0.45,
dimeFontNum = 4,
myfont_scale = 1.35,
x_angle = 45,
color_rect = c("-1"='red1', "0"='gray80',"1"='lightskyblue1'),
axis_name_y = "Countries",
axis_name_x = "Time",
alpha_color = 0.29
)

myGG
```

### Gamma_convergence

```{r}
gamma_conv(international_poverty_states_br,last=2021,ref=2012,timeName="time")
```

### Delta_convergence

```{r}
delta_conv(international_poverty_states_br,"time")
```

### Scoreboard

```{r}
resTB <- scoreb_yrs(international_poverty_states_br,timeName = "time")
resTB
```

```{r}
selectedCountry <- "X11"
timeName <- "time"
myx_angle <- 45
outSig <- sigma_conv(international_poverty_states_br, timeName = timeName,
time_0=2012,time_t=2021)
miniY <- min(international_poverty_states_br[,- which(names(international_poverty_states_br) == timeName )])
maxiY <- max(international_poverty_states_br[,- which(names(international_poverty_states_br) == timeName )])
estrattore<- international_poverty_states_br[,timeName] >= 2012 & international_poverty_states_br[,timeName] <= 2021
ttmp <- cbind(outSig$res, dplyr::select(international_poverty_states_br[estrattore,], -contains(timeName)))

myG2 <-
ggplot(ttmp) + ggtitle(
paste("Brazil average (black, solid) and country",selectedCountry ," (red, dotted)") )+
geom_line(aes(x=ttmp[,timeName], y =ttmp[,"mean"]),colour="black") +
geom_point(aes(x=ttmp[,timeName],y =ttmp[,"mean"]),colour="black") +
# geom_line()+geom_point()+
ylim(c(miniY,maxiY)) + xlab("Year") +ylab("Indicator") +
theme(legend.position = "none")+
# add countries
geom_line( aes(x=ttmp[,timeName], y = ttmp[,"X11"],colour="red"),linetype="dotted") +
geom_point( aes(x=ttmp[,timeName], y = ttmp[,"X11"],colour="red")) +
ggplot2::scale_x_continuous(breaks = ttmp[,timeName],
labels = ttmp[,timeName]) +
ggplot2::theme(
axis.text.x=ggplot2::element_text(
#size = ggplot2::rel(myfont_scale ),
angle = myx_angle
#vjust = 1,
#hjust=1
))
myG2

```

```{r}
obe_lvl <- scoreb_yrs(international_poverty_states_br, timeName = timeName)$res$sco_level_num
# select subset of time
estrattore <- obe_lvl[,timeName] >= 2012 & obe_lvl[,timeName] <= 2021
scobelvl <- obe_lvl[estrattore,]
my_MSstd <- ms_dynam(scobelvl,
timeName = "time",
displace = 0.25,
displaceh = 0.45,
dimeFontNum = 3,
myfont_scale = 1.35,
x_angle = 45,
axis_name_y = "States",
axis_name_x = "Time",
alpha_color = 0.9
)

my_MSstd

```